[package]
name = "defaults"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
consts.workspace = true
components.workspace = true
vehicle.workspace = true
rppal.workspace = true
