#!/usr/bin/env python3

LEFT_MOTOR_POWER_PIN = 13
LEFT_MOTOR_DIRECTION_PIN = 6
RIGHT_MOTOR_POWER_PIN = 12
RIGHT_MOTOR_DIRECTION_PIN = 5
IR_SENSOR_PIN = 17
NO_OF_SENSORS = 5
PWM_FREQUENCY = 4096
DEFAULT_SPEED = 100
IR_SENSOR_LEFT_PIN = 22
IR_SENSOR_RIGHT_PIN = 27
LIFT_POWER_PIN = 18
LIFT_DIRECTION_PIN = 26
SENSOR_THRESHOLD_LEFT = 180
SENSOR_THRESHOLD_RIGHT = 200
